### PR TITLE
Article page

### PR DESCRIPTION
**Pull request by WCanirinka**
We are requesting for a review

### CODE REVIEW

**Review by Redvanisation — CHANGES_REQUESTED** [review]
### Hello team  🌟

**Good work on this project, but we need to fix the issues below before moving on ⬇️** 

**1. Navbar**
- [x] The New York Times logo in the navbar should be a link.
- [x] It should have a fixed position (it sticks to the top part of the screen).


**2. Bottom part**
- [x]  It contains links to other articles with image previews on the leftmost side.
- [x]  It contains links to more popular articles on the rightmost side.

**3. Footer**
* [x] It should have a fixed position (it sticks to the bottom part of the screen).


**4. Linters** 

- [x] Set up Stickler to lint the CSS on your project, find out more on how to do that in [here](https://github.com/microverseinc/linters-config/tree/master/css)


### _After making the required changes please submit a new code review request_

### Good luck guys! 🍀

**Comment by tigamadou** [comment]
Hello. We are requesting for a new code review. Thanks.

**Comment by shloch** [comment]
### So much progress done since last review, 👍👍👍👍
good  job. One more thing, and we're good to go : 

**CHANGE REQUIRED** 

- You have successfully set up stickler, but you need to fix the errors stickler generates. Please work on that, let's move on . When you fix stickler errors, you wont see this red warning below
Screen Shot 2019-10-25 at 7 42 28 PM

**Comment by tigamadou** [comment]
All checks have passed for StyleLint...

**Comment by shshamim63** [comment]
## :tada:  Status -> Approved :tada: 
___
Hi @WCanirinka  and @genzaraki ,
Well done, All the required changes has been covered so far :slightly_smiling_face: . I will finish by mentioning on part. 
##### The navbar section should be inline. i can see the `subscribe for full access` part is not in inline. So you can apply a class to handle it, 
.subscribe-section {
    position : absolute;
    right: 0;
}  
##### please follow the instruction on the image and paste the code in the right bottom corner marked part to solve this issue.
newsweek
___

#### After solving this part you can merge it into master. This :+1:  is from me in advance.  
___

## Happy Coding :clubs: 
### Shakhawat Hossain
[Linkedin](https://www.linkedin.com/in/shakhawat-hossain-7750b0127/) | [Slack](Shakhawat Hossain)

**Pull request merged**
